### ISSUE TITLE
Add use cases in textual form for some representative user stories

### ISSUE THREAD

**Issue by aidoxe-123** [AY2021S1-CS2103T-W17-3/tp#11]

**Comment by JoeyChenSmart** [comment]
Added a skeleton to Duong's PR. Should be able to add on from there while avoiding merge conflicts.

(related note: can someone approve that PR? don't think I can do it because I also contributed a commit.)

We should use the same format as the one from AB3 (copied over below).

**Use case: Delete food**

**MSS**

1.  User requests to list persons
2.  AddressBook shows a list of persons
3.  User requests to delete a specific person in the list
4.  AddressBook deletes the person

    Use case ends.

**Extensions**

* 2a. The list is empty.

  Use case ends.

* 3a. The given index is invalid.

    * 3a1. AddressBook shows an error message.

      Use case resumes at step 2.
